### ISSUE TITLE
Passing Parameters to task

### ISSUE THREAD

**Issue by niektb** [MannyPeterson/HeliOS#24]
Hi! 
I had a question: is it possible to pass parameters to a task you're creating? 
So for example have two buttons but with a single task definition?
`void taskButton(xTaskId id_, const uint8_t port)`
which then is called with something like:
`
int p = 1;
id = xTaskAdd("TASKSW1", &taskSW, p)
`

**Comment by MannyPeterson** [comment]
@niektb not currently, but I am going to add this to the development backlog as I like the idea.

**Comment by MannyPeterson** [comment]
This feature will appear in 0.2.8

**Comment by MannyPeterson** [comment]
@niektb all done! Task parameters are now available in 0.3.0. Enjoy! :)

**Comment by niektb** [comment]
Sorry for getting back so late! Great news! I now worked around it using classes but this way is much more compact and elegant :D
