### ISSUE TITLE
Arduino Nano RP2040 Connect

### ISSUE THREAD

**Issue by berryempire** [MannyPeterson/HeliOS#27]
I'm trying to compile a HeliOS program for Arduino Nano RP2040 Connect (RP2040 processor from Raspberry Pi Pico), it says:

"This architecture is currently unsupported by HeliOS. If building for Linux or Microsoft Windows, make sure to un-comment OTHER_ARCH_LINUX or OTHER_ARCH_WINDOWS in HeliOS.h."
   #error "This architecture is currently unsupported by HeliOS. If building for Linux or Microsoft Windows, make sure to un-comment OTHER_ARCH_LINUX or OTHER_ARCH_WINDOWS in HeliOS.h."

Could you please add support for this architecture?
Thanks!

**Comment by MannyPeterson** [comment]
So built-in (tested) support still doesn't exist but it will no longer throw an error when compiling. So you should be able to run on RP2040. But I do plan on adding tested support.
